export const PAGE_SIZE = [
  { key: "1", value: "1", text: "1" },
  { key: "5", value: "5", text: "5" },
  { key: "10", value: "10", text: "10" },
];

export const TABLE_INFO = [
  {
    id: 1,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 2,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 3,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 4,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 5,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 6,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 7,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 8,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 9,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
  {
    id: 10,
    checked: false,
    name: "Lorem-ipsum_sitamet.jpg",
    fileCount: " ",
    dataCreated: "2021.09.30",
    dl: "0",
    size: "12.44 Mb",
    access: "public",
  },
];
